export type {
  GuardEvent,
  GuardRestartMetadata,
  GuardRestartReason,
  History,
  Process,
} from "../../dist/api.js";

export {
  db,
  getAllProcesses,
  getCurrentProcesses,
  getProcess,
  clearProcessOwnership,
  updateProcessOwnership,
  insertProcess,
  removeProcess,
  removeProcessByName,
  removeAllProcesses,
  updateProcessPid,
  updateProcessEnv,
  getAllTemplates,
  saveTemplate,
  deleteTemplate,
  getProcessHistory,
  getRecentHistory,
  getHistoryByEvent,
  getRecentHistoryByEvents,
  addHistoryEntry,
  getDependencyGraph,
  addDependency,
  removeDependency,
  getStartOrder,
  retryDatabaseOperation,
  getDbInfo,
  dbPath,
  bgrHome,
  isProcessRunning,
  isManagedProcessRunning,
  findManagedProcessPid,
  terminateProcess,
  readFileTail,
  getProcessPorts,
  findChildPid,
  findPidByPort,
  resolvePidWithPorts,
  getShellCommand,
  killProcessOnPort,
  waitForPortFree,
  ensureDir,
  getHomeDir,
  isWindows,
  getProcessBatchResources,
  getProcessMemory,
  reconcileProcessPids,
  handleRun,
  handleStop,
  stopProcess,
  deleteProcess,
  getManagedChildProcesses,
  ensureProcessWatcher,
  stopProcessWatcher,
  syncProcessWatcher,
  getGuardRestartCounts,
  getRecentGuardEvents,
  getErrorCode,
  getErrorMessage,
  hasErrorCode,
  historyRowToGuardEvent,
  parseGuardRestartMetadata,
  TimeoutError,
  retry,
  withTimeout,
  withTimeoutFallback,
  getVersion,
  calculateRuntime,
  parseEnvString,
  parseCommandEnv,
  stringifyEnvString,
  validateDirectory,
  isInternalProcessName,
  isWatcherProcessName,
  getWatcherProcessName,
  getWatchedProcessName,
} from "../../dist/api.js";

export { deployProcess, deployAllProcesses } from "../../dist/deploy.js";
export { buildDepGraph } from "../../dist/deps.js";
export { rotateAllLogs } from "../../dist/log-rotation.js";

import type { GuardEvent } from "../../dist/api.js";

/** Backward-compatible placeholders; persistent guard analytics live in history. */
export const guardEvents: GuardEvent[] = [];
export const guardRestartCounts = new Map<string, number>();
