export {
  db,
  getAllProcesses,
  getProcess,
  insertProcess,
  removeProcess,
  removeProcessByName,
  removeAllProcesses,
  updateProcessPid,
  updateProcessEnv,
  getAllTemplates,
  saveTemplate,
  deleteTemplate,
  getProcessHistory,
  getRecentHistory,
  addHistoryEntry,
  getDependencyGraph,
  addDependency,
  removeDependency,
  getStartOrder,
  getDbInfo,
  dbPath,
  bgrHome,
  isProcessRunning,
  terminateProcess,
  readFileTail,
  getProcessPorts,
  findChildPid,
  findPidByPort,
  resolvePidWithPorts,
  getShellCommand,
  killProcessOnPort,
  waitForPortFree,
  ensureDir,
  getHomeDir,
  isWindows,
  getProcessBatchResources,
  getProcessMemory,
  reconcileProcessPids,
  handleRun,
  handleStop,
  getManagedChildProcesses,
  ensureProcessWatcher,
  stopProcessWatcher,
  syncProcessWatcher,
  getGuardRestartCounts,
  getRecentGuardEvents,
  getVersion,
  calculateRuntime,
  parseEnvString,
  stringifyEnvString,
  validateDirectory,
  isInternalProcessName,
  isWatcherProcessName,
  getWatcherProcessName,
  getWatchedProcessName,
} from '../../dist/api.js'

export { deployProcess, deployAllProcesses } from '../../dist/deploy.js'
export { buildDepGraph } from '../../dist/deps.js'
export { rotateAllLogs } from '../../dist/log-rotation.js'

export const guardEvents: any[] = []
export const guardRestartCounts = new Map<string, number>()
